# Feature Extraction

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['Pe Wa Ca','Ca Wa Ca','Pe WR Co','Ca WR Co',],'output':[1,1,0,0]})

In [16]:
df

text  output
0  Pe Wa Ca       1
1  Ca Wa Ca       1
2  Pe WR Co       0
3  Ca WR Co       0

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer()

## BAG of Words

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'pe': 2, 'wa': 3, 'ca': 0, 'wr': 4, 'co': 1}


In [22]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [24]:
cv.transform(['ca wa and wr co of ca']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

## N-grams

### ngram_range is used

In [28]:
# cv = CountVectorizer(ngram_range=(2,2))
# cv = CountVectorizer(ngram_range=(1,2))
cv = CountVectorizer(ngram_range=(1,3))

In [29]:
bow = cv.fit_transform(df['text'])

In [30]:
print(cv.vocabulary_)

{'pe': 6, 'wa': 11, 'ca': 0, 'pe wa': 7, 'wa ca': 12, 'pe wa ca': 8, 'ca wa': 1, 'ca wa ca': 2, 'wr': 13, 'co': 5, 'pe wr': 9, 'wr co': 14, 'pe wr co': 10, 'ca wr': 3, 'ca wr co': 4}


# TFIDF

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [8]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['ca' 'co' 'pe' 'wa' 'wr']
